"""Create telemetry and lane_hints tables

Revision ID: ad531a56a231
Revises: 
Create Date: 2026-01-18 17:21:06.746527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad531a56a231'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lane_hints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geohash', sa.String(length=10), nullable=True),
    sa.Column('heading_bucket', sa.Integer(), nullable=True),
    sa.Column('recommended_lanes', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_geohash_heading_hint', 'lane_hints', ['geohash', 'heading_bucket'], unique=False)
    op.create_index(op.f('ix_lane_hints_geohash'), 'lane_hints', ['geohash'], unique=False)
    op.create_index(op.f('ix_lane_hints_id'), 'lane_hints', ['id'], unique=False)
    op.create_table('telemetry_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geohash', sa.String(length=10), nullable=True),
    sa.Column('heading_bucket', sa.Integer(), nullable=True),
    sa.Column('speed_bucket', sa.Integer(), nullable=True),
    sa.Column('lane_count_estimate', sa.Integer(), nullable=True),
    sa.Column('recommended_lanes', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_geohash_heading', 'telemetry_events', ['geohash', 'heading_bucket'], unique=False)
    op.create_index(op.f('ix_telemetry_events_geohash'), 'telemetry_events', ['geohash'], unique=False)
    op.create_index(op.f('ix_telemetry_events_id'), 'telemetry_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_events_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_geohash'), table_name='telemetry_events')
    op.drop_index('idx_geohash_heading', table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index(op.f('ix_lane_hints_id'), table_name='lane_hints')
    op.drop_index(op.f('ix_lane_hints_geohash'), table_name='lane_hints')
    op.drop_index('idx_geohash_heading_hint', table_name='lane_hints')
    op.drop_table('lane_hints')
    # ### end Alembic commands ###
